# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-08 13:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Servers',
            fields=[
                ('server_id', models.CharField(max_length=90, primary_key=True, serialize=False, unique=True)),
                ('server_status', models.BooleanField(default=False)),
            ],
        ),
    ]
